In [5]:
# 1.	Write a Python Program to Add Two Matrices?

import numpy as np

arr1 = np.arange(5,5)
arr2 = np.linspace(-1,1,25)
arr1

array([], dtype=int64)

In [17]:
arr1 = np.arange(25).reshape(5,5)

In [23]:
arr2 = arr2.reshape(5,5)

In [24]:
np.add(arr1,arr2)

array([[-1.        ,  0.08333333,  1.16666667,  2.25      ,  3.33333333],
       [ 4.41666667,  5.5       ,  6.58333333,  7.66666667,  8.75      ],
       [ 9.83333333, 10.91666667, 12.        , 13.08333333, 14.16666667],
       [15.25      , 16.33333333, 17.41666667, 18.5       , 19.58333333],
       [20.66666667, 21.75      , 22.83333333, 23.91666667, 25.        ]])

In [34]:
new_arr = []
for itm, value  in zip(arr1,arr2):
    new_arr.append(itm+value)

In [35]:
new_arr

[array([-1.        ,  0.08333333,  1.16666667,  2.25      ,  3.33333333]),
 array([4.41666667, 5.5       , 6.58333333, 7.66666667, 8.75      ]),
 array([ 9.83333333, 10.91666667, 12.        , 13.08333333, 14.16666667]),
 array([15.25      , 16.33333333, 17.41666667, 18.5       , 19.58333333]),
 array([20.66666667, 21.75      , 22.83333333, 23.91666667, 25.        ])]

In [25]:
# 2.	Write a Python Program to Multiply Two Matrices?

np.matmul(arr1,arr2)

array([[  2.5       ,   3.33333333,   4.16666667,   5.        ,
          5.83333333],
       [ -1.66666667,   1.25      ,   4.16666667,   7.08333333,
         10.        ],
       [ -5.83333333,  -0.83333333,   4.16666667,   9.16666667,
         14.16666667],
       [-10.        ,  -2.91666667,   4.16666667,  11.25      ,
         18.33333333],
       [-14.16666667,  -5.        ,   4.16666667,  13.33333333,
         22.5       ]])

In [27]:
# 3.	Write a Python Program to Transpose a Matrix?

arr1.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [38]:
# 4.	Write a Python Program to Sort Words in Alphabetic Order?

x = ["banana","apple","grapes","papaya","mango"]
x.sort(reverse=True)
x

['papaya', 'mango', 'grapes', 'banana', 'apple']

In [45]:
# 5.	Write a Python Program to Remove Punctuation From a String?
import string

translator = str.maketrans('','',string.punctuation)
x = "What a good weather! it is today!  Indeed it's a very good weather  right"
x.translate(translator)

'What a good weather it is today  Indeed its a very good weather  right'

In [47]:
''.join(word for word in x if word not in string.punctuation)

'What a good weather it is today  Indeed its a very good weather  right'